#target aftereffects
(function(){
 var helper="\n/* lokaya-direct-title-v1 */\nfunction lkIsArrangedGlass(items){for(var i=0;i<items.length;i++)if(items[i] instanceof CompItem&&items[i].name==='Glass Object')return true;return false;}\nfunction lkDirectGlassTitle(source,items){if(!lkIsArrangedGlass(items))return source;if(source instanceof CompItem&&source.name==='Glass Object'&&source.numLayers===1){var inner=source.layer(1).source;if(inner instanceof CompItem&&/title/i.test(inner.name))return inner;throw Error('Glass Object does not contain the expected Title composition.');}return source;}\n";
 var shapeHelper="\n/* lokaya-inner-stars-v2 */\nfunction lkPrepareGlassShape(source,items){\n if(!(source instanceof CompItem)||!/^Title 0[1-4]$/.test(source.name))return;\n var isShape=false;\n for(var i=0;i<items.length;i++){var c=items[i];if(c instanceof CompItem&&c.name==='Final '+source.name){for(var j=1;j<=c.numLayers;j++)if(c.layer(j).source===source)isShape=true;}}\n if(!isShape)return;\n for(var n=1;n<=source.numLayers;n++){var layer=source.layer(n);if(layer.canSetCollapseTransformation)layer.collapseTransformation=false;}\n}\n";
 var repairHelper="\n/* lokaya-title-resolution-v3 */\nfunction lkDirectGlassTitle(source,items){\n if(!lkIsArrangedGlass(items))return source;\n var wrapper=null;for(var i=0;i<items.length;i++)if(items[i] instanceof CompItem&&items[i].name==='Glass Object'){if(wrapper)throw Error('Multiple Glass Object wrappers');wrapper=items[i];}\n if(!wrapper||wrapper.numLayers!==1)throw Error('Invalid Glass Object wrapper');\n var title=wrapper.layer(1).source;\n if(!(title instanceof CompItem)||!/title/i.test(title.name))throw Error('Missing linked Title composition');\n // Follow the actual layer source, never another composition with the same name.\n if(/^Final Title 0[1-4]$/.test(title.name)){\n  var linked=null;var expected=title.name.replace(/^Final /,'');\n  for(var n=1;n<=title.numLayers;n++){var child=title.layer(n).source;if(child instanceof CompItem&&child.name===expected){if(linked&&linked!==child)throw Error('Multiple linked Titles');linked=child;}}\n  if(!linked)throw Error('Missing linked '+expected);title=linked;\n }\n return title;\n}\nfunction lkPrepareGlassShape(source,items){\n if(!(source instanceof CompItem)||!/^Title 0[1-4]$/.test(source.name))return;\n var isShape=false;\n for(var i=0;i<items.length;i++){var c=items[i];if(c instanceof CompItem&&c.name==='Final '+source.name){for(var j=1;j<=c.numLayers;j++)if(c.layer(j).source===source)isShape=true;}}\n if(!isShape)return;\n for(var n=1;n<=source.numLayers;n++){var layer=source.layer(n);if(!layer.canSetCollapseTransformation||!layer.collapseTransformation)continue;var locked=layer.locked;\n  try{if(locked)layer.locked=false;layer.collapseTransformation=false;if(layer.collapseTransformation)throw Error('Could not disable star: '+layer.name);}finally{layer.locked=locked;}\n }\n}\n";
 function patch(s){if(s.indexOf("lokaya-title-resolution-v3")>=0)return s;return legacyPatch(s)+repairHelper;}
 var roots=[Folder.userData.fsName+'/Adobe/CEP/extensions',Folder.appData.fsName+'/Adobe/CEP/extensions','/Library/Application Support/Adobe/CEP/extensions',Folder('~/Library/Application Support/Adobe/CEP/extensions').fsName,'C:/Program Files (x86)/Common Files/Adobe/CEP/extensions','C:/Program Files/Common Files/Adobe/CEP/extensions'];
 var done={},count=0,errors=[];
 function legacyPatch(s){
  if(s.indexOf('lokaya-inner-stars-v2')>=0)return s;
  if(s.indexOf('lokaya-direct-title-v1')>=0){var oldMarker='added = target.layers.add(source);';if(s.indexOf(oldMarker)<0)throw Error('Unsupported importer');return s.replace(oldMarker,'lkPrepareGlassShape(source,introduced);\n        '+oldMarker)+shapeHelper;}
  var marker='added = target.layers.add(source);';
  if(s.indexOf('lkElementsImport')<0||s.indexOf(marker)<0||s.indexOf('introduced')<0)throw Error('Unsupported Elements importer. No files changed.');
  // Repair an older optional bilingual helper without forcing English into RTL.
  s=s.replace(/t\.direction=ParagraphDirection\.DIRECTION_RIGHT_TO_LEFT;/g,"t.direction=/[\\u0600-\\u06ff\\u0750-\\u077f\\u08a0-\\u08ff]/.test(t.text)?ParagraphDirection.DIRECTION_RIGHT_TO_LEFT:ParagraphDirection.DIRECTION_LEFT_TO_RIGHT;");
  s=s.replace(/v\.direction!==ParagraphDirection\.DIRECTION_RIGHT_TO_LEFT/g,'v.direction!==t.direction');
  return s.replace(marker,"var lkDirectTitle = kind === 'aep' && lkIsArrangedGlass(introduced);\n        if(lkDirectTitle) source = lkDirectGlassTitle(source,introduced);\n        lkPrepareGlassShape(source,introduced);\n        "+marker+"\n        if(lkDirectTitle){if(!added.canSetCollapseTransformation)throw Error('Cannot enable Collapse Transformations for '+source.name);added.collapseTransformation=true;}")+helper+shapeHelper;
 }
 for(var ri=0;ri<roots.length;ri++){var root=new Folder(roots[ri]);if(!root.exists)continue;var dirs=root.getFiles(function(f){return f instanceof Folder;});
 for(var di=0;di<dirs.length;di++){var f=new File(dirs[di].fsName+'/jsx/elements_import.jsx');if(!f.exists||done[f.fsName])continue;done[f.fsName]=true;
 try{f.encoding='UTF-8';if(!f.open('r'))throw Error('Cannot read '+f.fsName);var s=f.read();f.close();var p=patch(s);
 if(p!==s){var backup=new File(f.fsName+'.before-title-resolution-v3.bak');if(!backup.exists&&!f.copy(backup.fsName))throw Error('Cannot back up '+f.fsName);if(!f.open('w'))throw Error('Cannot write '+f.fsName);f.write(p);f.close();}count++;
 }catch(e){errors.push(String(e));}}
 }
 if(!count){alert('Lokaya update failed. '+errors.join('\n'));return;}
 alert('Lokaya updated: double-click imports the Title composition directly with the outer star enabled; the four Glass Shapes have inner stars disabled. Restart After Effects, refresh Elements, then add the element again.'+(errors.length?'\nOther installations: '+errors.join('\n'):''));
})();
