#target aftereffects
(function(){
 var roots=[Folder.userData.fsName+'/Adobe/CEP/extensions',Folder.appData.fsName+'/Adobe/CEP/extensions'];
 if($.os.toLowerCase().indexOf('windows')>=0){roots.push('C:/Program Files (x86)/Common Files/Adobe/CEP/extensions');roots.push('C:/Program Files/Common Files/Adobe/CEP/extensions');}
 else{roots.push('/Library/Application Support/Adobe/CEP/extensions');roots.push(Folder('~/Library/Application Support/Adobe/CEP/extensions').fsName);}
 var candidates=[];for(var r=0;r<roots.length;r++){var d=new Folder(roots[r]);if(d.exists){var dirs=d.getFiles(function(f){return f instanceof Folder;});for(var n=0;n<dirs.length;n++){var f=new File(dirs[n].fsName+'/js/elements_library.js');if(f.exists)candidates.push(f);}}}
 if(!candidates.length){var chosen=Folder.selectDialog('Select the installed Lokaya extension folder');if(!chosen)return;candidates.push(new File(chosen.fsName+'/js/elements_library.js'));}
 var done=0,errors=[];
 for(var i=0;i<candidates.length;i++){
  var file=candidates[i];try{
   file.encoding='UTF-8';if(!file.open('r'))throw Error('Cannot read '+file.fsName);var old=file.read();file.close();
   if(old.indexOf("lkyElementsGrid")<0||old.indexOf('LokayaElementsTransfer')<0)continue;
   if(old.indexOf("lokaya_elements_seen_v1")>=0){done++;continue;}
   var next=old;
   var helpers="\n var seenKey='lokaya_elements_seen_v1',cacheKey='lokaya_elements_catalog_v1',seen={},loading=false,lastCheck=0;\n try{seen=JSON.parse(localStorage.getItem(seenKey)||'{}')||{};}catch(e){}\n (window.LokayaElementsCatalog.items||[]).forEach(function(i){if(!i.isNew)seen[i.id]=true;});\n function isNew(i){return !seen[i.id];}\n function markSeen(i){seen[i.id]=true;try{localStorage.setItem(seenKey,JSON.stringify(seen));}catch(e){}updateCount();}\n function updateCount(){var n=items.filter(isNew).length;document.getElementById('lkyElementsCount').textContent=items.filter(function(i){return category==='all'||i.category===category;}).length+' '+tr('عنصر','elements')+(n?' • '+n+' '+tr('جديد','NEW'):'');}\n function acceptCatalog(c){if(!c||!Array.isArray(c.items)||[1,2,3].indexOf(Number(c.version))<0)throw Error('Invalid library catalog');var a=c.items.filter(transfer.validate);if(!a.length||a.length!==c.items.length)throw Error('Invalid library items');return a;}\n async function refreshCatalog(){\n  if(loading||busy)return;loading=true;lastCheck=Date.now();notice.textContent=tr('جاري التحقق من العناصر الجديدة…','Checking for new elements…');\n  try{\n   setup();var c;\n   try{c=JSON.parse(await transfer.text(URL+'?t='+Date.now()));}\n   catch(first){var api=JSON.parse(await transfer.text('https://api.github.com/repos/lokaya0/lokaya-projects/contents/elements-catalog-v3.json?ref=main'));var req=window.cep_node&&window.cep_node.require?window.cep_node.require.bind(window.cep_node):window.require;c=JSON.parse(req('buffer').Buffer.from(api.content,'base64').toString('utf8'));}\n   var a=acceptCatalog(c);items=a;try{localStorage.setItem(cacheKey,JSON.stringify(c));}catch(e){}render();notice.textContent=items.filter(isNew).length?tr('أكو عناصر جديدة — عليها علامة NEW.','New elements available — marked NEW.'):tr('المكتبة محدثة.','Library is up to date.');notice.title='';\n  }catch(e){notice.textContent=tr('تعذّر التحديث أونلاين. اضغط تحديث للمحاولة مجدداً. ','Online update failed. Press Refresh to retry. ')+String(e.message||e);notice.title=String(e.message||e);}\n  finally{loading=false;}\n }\n var style=document.createElement('style');style.textContent='.lky-el-card{position:relative}.lky-el-new{position:absolute;top:8px;right:8px;background:var(--accent,#397d69);color:#fff;border-radius:6px;padding:3px 7px;font:bold 10px sans-serif;z-index:1}.lky-el-refresh{float:right;cursor:pointer;border:1px solid var(--border,#aaa);border-radius:6px;background:var(--panel,transparent);color:inherit;padding:4px 10px;margin:3px 8px}';document.head.appendChild(style);\n var refreshButton=document.createElement('button');refreshButton.type='button';refreshButton.className='lky-el-refresh';refreshButton.textContent=tr('تحديث','Refresh');refreshButton.onclick=refreshCatalog;document.getElementById('lkyElementsCount').parentNode.insertBefore(refreshButton,document.getElementById('lkyElementsCount'));\n";
   if(next.indexOf(' function render(){')<0)throw Error('Unexpected library version');
   next=next.replace(' function render(){',helpers+'\n function render(){');
   next=next.replace("document.getElementById('lkyElementsCount').textContent=filtered.length+' '+tr('عنصر','elements');","updateCount();");
   next=next.replace('   card.appendChild(media);',"   card.appendChild(media);if(isNew(i)){var badge=document.createElement('span');badge.className='lky-el-new';badge.textContent='NEW';card.appendChild(badge);card.addEventListener('click',function(){markSeen(i);if(badge.parentNode)badge.parentNode.removeChild(badge);});}");
   var start=next.indexOf(' async function boot(){'),end=next.indexOf(" window.addEventListener('resize',fit);",start);
   if(start<0||end<0||next.indexOf('function refreshCatalog')<0)throw Error('Unexpected library version');
   next=next.substring(0,start)+" async function boot(){\n  fit();if(booted){if(Date.now()-lastCheck>30000)refreshCatalog();return;}booted=true;\n  items=(window.LokayaElementsCatalog.items||[]).filter(validItem);\n  try{setup();var saved=localStorage.getItem(cacheKey);if(saved)items=acceptCatalog(JSON.parse(saved));}catch(e){}\n  render();refreshCatalog();\n }\n window.addEventListener('focus',function(){if(pane.classList.contains('active')&&Date.now()-lastCheck>30000)refreshCatalog();});\n setInterval(function(){if(pane.classList.contains('active')&&!document.hidden&&Date.now()-lastCheck>300000)refreshCatalog();},300000);\n"+next.substring(end);
   var backup=new File(file.fsName+'.before-new-update.bak');if(!backup.exists&&!file.copy(backup.fsName))throw Error('Cannot back up file');
   if(!file.open('w'))throw Error('Cannot write '+file.fsName+'; check folder permissions');
   if(!file.write(next)){file.close();backup.copy(file.fsName);throw Error('Write failed');}file.close();done++;
  }catch(e){errors.push(e.toString());}
 }
 if(done)alert('Lokaya Elements updated. Close and reopen the Lokaya panel. New items are marked NEW. No full reinstall needed.');
 if(errors.length)alert('Some locations could not be updated:\n'+errors.join('\n'));
 if(!done&&!errors.length)alert('Lokaya library file not found.');
})();
